import React from "react";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";

// Default metadata for all pages
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Export static params for Next.js to pre-render each locale
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type AvailableLocale = (typeof routing.locales)[number];

export default async function ContentLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  // `params` is declared as a Promise of the object.
  params: Promise<{ locale: AvailableLocale }>;
}) {
  // Await the params before using its properties
  const { locale } = await params;

  // Validate the locale
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Enable static rendering for this locale
  setRequestLocale(locale);

  return (
    <div className='leading-loose text-sm'>
        {children}
    </div>
  );
}
